### ISSUE TITLE
update README / manual with missing info 

### ISSUE THREAD

**Issue by nameles-admin** [Nameles-Org/Nameles-logfile#3]
Can you make sure that the README/manual is consistent with the way you've tested the deb / source installations to work. If there are some known issues in the installation process, I don't think we need to worry about it too much, but just make sure we have an open issue for each.

**Comment by apastor** [comment]
Updated the README with the info from the INSTALL file. Please, @mikkokotila, can you double check that the instructions work and everything is correct?

Besides, maybe the last section of the readme could reflect that log file has to be in CSV format and compressed with gunzip (.csv.gz).
