### ISSUE TITLE
dealing with install failing on 16.04

### ISSUE THREAD

**Issue by mikkokotila** [Nameles-Org/Nameles-logfile#6]
It seems that the install is pretty smooth with Ubuntu 16.04. First have to install psql, and then follow the install instructions. Now the next step for is to make the initial install failure due to dependencies go away, and then I can add Travis to this repo. Can you explain why it happens, and I can write a script to overcome it.

**Comment by apastor** [comment]
Dpkg does not install dependencies. For installing the dependencies automatically you can use gdebi, but it is not usually installed by default. You can install just the command line client from apt (`sudo apt-get install gdebi-core`) and run then do `sudo gdebi <package.deb>` to install the package.

It prompts for confirmation, but you can use the `-n` flag to avoid it. Something to consider is that the non-interactive install overwrites any config file when updating a package. Although I think that it should not be a problem for us.
