### ISSUE TITLE
handling machines with small memory (vm for example)

### ISSUE THREAD

**Issue by mikkokotila** [Nameles-Org/Nameles-logfile#7]
It seems that it would be easy to fix setup script so that when machine only has 1gb ram, it will still work. It works just fine after the manual config, but of course not for big files. Most people do not deal with big files actually for the research purpose (by big I mean billions of rows).

**Comment by apastor** [comment]
The minimum values for the number of cores and memory are now controlled on the `nameles-log-migration`script. Starting on version 0.2.
